CycloneSolutions/force-app/main/default/objects/Widget__c/Widget__c.object-meta.xml
<CustomObject>
    <description>Save records of Enpal Challenge.</description>
    <label>Widget</label>
    <nameField>
        <displayFormat>W-{00000}</displayFormat>
        <label>Widget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Widgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Widget__c/fields/CS_IsChecked__c.field-meta.xml
<CustomField>
    <fullName>CS_IsChecked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Auxiliary field to check if Value is porperly nested has been evaluated.</description>
    <label>IsChecked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Widget__c/fields/CS_IsProperlyNested__c.field-meta.xml
<CustomField>
    <fullName>CS_IsProperlyNested__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if Value field String is properly nested (Brackets)</description>
    <label>Is Properly Nested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Widget__c/fields/CS_Value__c.field-meta.xml
<CustomField>
    <fullName>CS_Value__c</fullName>
    <description>Text field that saves string information</description>
    <label>Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CS_WidgetIsValueProperlyNested.cls
public class CS_WidgetIsValueProperlyNested implements Schedulable{
    
    public void execute(SchedulableContext SC) {
        CS_WidgetIsValueProperlyNested();
         
    }

    public static void CS_WidgetIsValueProperlyNested() {
        
        List<Widget__c> widgetList = [
            SELECT id, CS_Value__c, CS_IsProperlyNested__c
            FROM Widget__c
            WHERE CS_IsChecked__c = false
        ]; 

        if (!widgetList.IsEmpty()) {
            for (Widget__c widget : widgetList) {

                widget.CS_IsChecked__c = true;

                widget.CS_IsProperlyNested__c = checkValue(widget.CS_Value__c);
            }
            
            update widgetList;
        }

    }

    //Method check if string is properly nested
    public static Boolean checkValue(String value){
        
        Set<String> bracketsControl = new Set<String>{'(',')','{','}','[',']'};
        List<String> brackets = new List<String>();
        
        if (!String.isEmpty(value)) {
            
            //loop each char in the string
            for (Integer i = 0; i < value.length(); i++) {                
               
                String charact = value.substring(i,i+1);
                
                //check if the element is a bracket
                if (!bracketsControl.contains(charact)) {
                    continue; 
                }
                
                
                //check if the charact is a open bracket
                if (charact == '(' || charact == '[' || charact == '{'){
                    
                    // Add the element in the brackets
                    brackets.add(charact);
                    continue;               
                }
    
                // if the previous elements arent open brackets automatically 
                //is not propertly nested
                if (brackets.size()==0){
    
                    return false;
                }
    
                //Check on close brackets and last added bracked to the opening brackets
                String lastBracket;
                if( charact == ')'){
    
                    lastBracket = brackets.remove(brackets.size()-1);
    
                    if (lastBracket == '{' || lastBracket == '['){
                       return false;
                    }                    
                }else if( charact == '}'){
    
                    lastBracket = brackets.remove(brackets.size()-1);
    
                    if (lastBracket == '(' || lastBracket == '['){
                        return false;
                    }
                }else if( charact == ']'){
    
                    lastBracket = brackets.remove(brackets.size()-1);
                    
                    if (lastBracket == '(' || lastBracket == '{'){
                        return false;
                    }
                }
            }
        }
        
        return (brackets.size()==0);
    }

    //Method to be call by flow 'WidgetInputScreen' (Only recive and acpts)
    @InvocableMethod
    public static List<Boolean> flowCheckValue(List<String> valueList){
        List<Boolean> checkValueResponce = new List<Boolean>();
        Boolean responce;
        for (String value : valueList) {
            responce = checkValue(value);
            checkValueResponce.add(responce);                     
        }
        return checkValueResponce;
    }

}